### ISSUE TITLE
Introduce BCD Converter

### ISSUE THREAD

**Issue by akshitadixit** [DSC-IIIT-Kalyani/ENCODN#10]
#### Feature Request:
It would be nice to have a BCD converter in ENCODN

#### Solution required:
1. Add a .py file with the named **BCD.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the BCD encrypted string.
2. In BCD.py add another function definition by the name **decrypt(String)** that takes in a BCD encrypted string and returns the plaintext string corresponding to it. Return "The entered hash/cypher/value is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/ELECTRONICS/BCD/** directory only, the filename, function name should be as specified above (case sensitive).

**Comment by ieternalleo** [comment]
Can this be assigned to me, please. I would like to work on this
