### ISSUE TITLE
Add SHA-1 hash technique

### ISSUE THREAD

**Issue by akshitadixit** [DSC-IIIT-Kalyani/ENCODN#2]
#### Feature Request:
It would be nice to have a hashing algorithm like SHA-1 in ENCODN

#### Solution required:
1. Add a .py file with the named **SHA-1.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the hashed string.
2. In SHA-1.py add another function definition by the name **decrypt(String)** that takes in a SHA-1 hashed string and returns the plaintext string corresponding to it. Return "The entered hash is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/CRYPTOGRAPHY/MODERN CRPYTOGRAPHY/** directory only, the filename, function name should be as specified above (case sensitive).

**Comment by Ramas1998** [comment]
@akshitadixit 
I am ready for this, please assign me this issue.
