### ISSUE TITLE
Introduce MD4 encryption-decryption algorithm

### ISSUE THREAD

**Issue by akshitadixit** [DSC-IIIT-Kalyani/ENCODN#21]
#### Feature Request:
It would be nice to have a hashing algorithm like MD4 in ENCODN

#### Solution required:
1. Add a .py file with the named **MD4.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the MD4 encrypted string.
2. In MD4.py add another function definition by the name **decrypt(String)** that takes in a MD4 encypted string and returns the plaintext string corresponding to it. Return "The entered hash/cypher/value is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/CRYPTOGRAPHY/MODERN CRYPTOGRAPHY/MD4/** directory only, the filename, function name should be as specified above (case sensitive).

**Comment by rexdivakar** [comment]
Assign it to me will raise a PR @akshitadixit

**Comment by rexdivakar** [comment]
Are u expecting to encrypt the text or hash it ?

**Comment by akshitadixit** [comment]
We're expecting a hash.

**Comment by rexdivakar** [comment]
oh k i will work on it now

**Comment by rexdivakar** [comment]
md4 hash is outdated, how about md5 ??

**Comment by rexdivakar** [comment]
well technically md5 is not encryption its a hashing method, but i will make changes for ur needs !!
