### ISSUE TITLE
Introduce Rozier Cypher

### ISSUE THREAD

**Issue by akshitadixit** [DSC-IIIT-Kalyani/ENCODN#22]
#### Feature Request:
It would be nice to have a cypher algorithm like Rozier in ENCODN

#### Solution required:
1. Add a .py file with the named **ROZIER.py** and add a function definition by the name **encrypt(String)** that takes in a plaintext string as input and returns the encrypted string.
2. In ROZIER..py add another function definition by the name **decrypt(String)** that takes in an encypted string and returns the plaintext string corresponding to it. Return "The entered hash/cypher/value is incorrect!!!" in case of discrepancies.

#### Additional Info:
The file should be stored in the **ENCODN/ENCODN/TOOLS/CRYPTOGRAPHY/OTHER/ROZIER/** directory only, the filename, function name should be as specified above (case sensitive).

**Comment by MrLukeKR** [comment]
Hi there, could I be assigned to this, please?

**Comment by MrLukeKR** [comment]
Hi there, I'd like to work on this, could I be assigned to the task, please?

**Comment by MrLukeKR** [comment]
Hi there, I would like to work on this, can I be assigned, please?
